### ISSUE TITLE
issue downloading package

### ISSUE THREAD

**Issue by saraswaminathan** [shgroves/NCRMP_benthics#4]
hi there, I get the following error message when I try to install the ncrmp.benthics.analysis package from within the R project of the same name. Do you have any suggestions for installing the package? Thank you! 

Error in `package_file()`:
! Could not find package root.
ℹ Is . inside a package?

**Comment by Jordan-Pierce** [comment]
Hi @saraswaminathan can you confirm that you are working in the sub-directory:

`NCRMP_benthics/ncrmp.benthics.analysis/`

And not the root of the GitHub repo:

`NCRMP_benthics/`

There is an Rproj file in the root of the GitHub repo, but the correct one is:

`NCRMP_benthics/ncrmp.benthics.analysis/ncrmp.benthics.analysis.Rproj`

@blwilliams02

**Comment by saraswaminathan** [comment]
yes confirmed

**Comment by blwilliams02** [comment]
Hi Sara @saraswaminathan,

The error you're getting sounds like you're working in the wrong package when you try to run the installation. You need to use the R project titled "ncrmp.benthics.analysis.Rproj" **NOT** the one titled "NCRMP_benthics.Rproj" Below are the installation instructions. If you're still having issues, reach out to me directly at bethany.williams@noaa.gov.


**Installation using devtools:**
1. Download the zipped R package using the green "Clone or download" button.

2. In R studio, open the ncrmp.benthics.analysis R project in the folder of the same name and use the following code to install the package. You must be in the ncrmp.benthics.analysis R project. If you aleady have devtools installed you can skip the first line.

install.packages('devtools')

devtools::install()

3. Exit the ncrmp.benthics.analysis R project and check your R library to confirm the package installed. At this point you can either delete the files from the zipped folder or retain them if you are interested in the analysis code.

4. From your current project, use the following code to load and use the package.

library(ncrmp.benthics.analysis) 

5. To update the package (when new data is added), repeat steps 1-4. If you are having trouble, try deleting the old version first before intalling the new one.
Note: Requires R version 3.4.1 or higher.

**Comment by shgroves** [comment]
One minor but important step that many people have omitted is that you must
unzip the downloaded file before you open the ncrmp.benthics.analysis
project for installation.

Sarah

-----------------------
Sarah H. Groves (she/her)
Data Analyst
Science & Technology Division
NOAA Ocean Exploration


*C: 225-382-7801*

**Comment by saraswaminathan** [comment]
Hi all, thank you - I was in the write project, but Sarah's suggestion helped - it hadn't unzipped! Thank you very much

**Comment by shgroves** [comment]
Hi Sara,

Apologies, the instructions should be more clear! We will update the
landing page to include that step.

Sarah

-----------------------
Sarah H. Groves (she/her)
Data Analyst
Science & Technology Division
NOAA Ocean Exploration


*C: 225-382-7801*

**Comment by Jordan-Pierce** [comment]
Great, closing the issue.
